// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Value = stardog::webfunction::types::Value;
pub type BindingSets = stardog::webfunction::types::BindingSets;
pub type Cardinality = stardog::webfunction::types::Cardinality;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_evaluate_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base18 = arg0;
    let len18 = arg1;
    let mut result18 = _rt::Vec::with_capacity(len18);
    for i in 0..len18 {
        let base = base18.add(i * (8 * ::core::mem::size_of::<*const u8>()));
        let e18 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            use stardog::webfunction::types::Value as V17;
            let v17 = match l0 {
                0 => {
                    let e17 = {
                        let l1 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l2 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len3 = l2;
                        let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                        _rt::string_lift(bytes3)
                    };
                    V17::Iri(e17)
                }
                1 => {
                    let e17 = {
                        let l4 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                        let l7 = *base
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l8 = *base
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                        let l10 = i32::from(
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>(),
                        );
                        stardog::webfunction::types::Literal {
                            label: _rt::string_lift(bytes6),
                            datatype: _rt::string_lift(bytes9),
                            lang: match l10 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l11 = *base
                                            .add(6 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l12 = *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        }
                    };
                    V17::Literal(e17)
                }
                n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    let e17 = {
                        let l14 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l15 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len16 = l15;
                        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
                        _rt::string_lift(bytes16)
                    };
                    V17::Bnode(e17)
                }
            };
            v17
        };
        result18.push(e18);
    }
    _rt::cabi_dealloc(
        base18,
        len18 * (8 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result19 = T::evaluate(result18);
    let ptr20 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result19 {
        Ok(e) => {
            *ptr20.add(0).cast::<u8>() = (0i32) as u8;
            let stardog::webfunction::types::BindingSets {
                vars: vars21,
                rows: rows21,
            } = e;
            let vec23 = vars21;
            let len23 = vec23.len();
            let layout23 = _rt::alloc::Layout::from_size_align_unchecked(
                vec23.len() * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result23 = if layout23.size() != 0 {
                let ptr = _rt::alloc::alloc(layout23).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout23);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec23.into_iter().enumerate() {
                let base = result23.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let vec22 = (e.into_bytes()).into_boxed_slice();
                    let ptr22 = vec22.as_ptr().cast::<u8>();
                    let len22 = vec22.len();
                    ::core::mem::forget(vec22);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
                    *base.add(0).cast::<*mut u8>() = ptr22.cast_mut();
                }
            }
            *ptr20.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
            *ptr20.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result23;
            let vec34 = rows21;
            let len34 = vec34.len();
            let layout34 = _rt::alloc::Layout::from_size_align_unchecked(
                vec34.len() * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result34 = if layout34.size() != 0 {
                let ptr = _rt::alloc::alloc(layout34).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout34);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec34.into_iter().enumerate() {
                let base = result34.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let vec33 = e;
                    let len33 = vec33.len();
                    let layout33 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec33.len() * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result33 = if layout33.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout33).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout33);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec33.into_iter().enumerate() {
                        let base = result33
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let stardog::webfunction::types::Binding {
                                name: name24,
                                value: value24,
                            } = e;
                            let vec25 = (name24.into_bytes()).into_boxed_slice();
                            let ptr25 = vec25.as_ptr().cast::<u8>();
                            let len25 = vec25.len();
                            ::core::mem::forget(vec25);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len25;
                            *base.add(0).cast::<*mut u8>() = ptr25.cast_mut();
                            use stardog::webfunction::types::Value as V32;
                            match value24 {
                                V32::Iri(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec26 = (e.into_bytes()).into_boxed_slice();
                                    let ptr26 = vec26.as_ptr().cast::<u8>();
                                    let len26 = vec26.len();
                                    ::core::mem::forget(vec26);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len26;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr26.cast_mut();
                                }
                                V32::Literal(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let stardog::webfunction::types::Literal {
                                        label: label27,
                                        datatype: datatype27,
                                        lang: lang27,
                                    } = e;
                                    let vec28 = (label27.into_bytes()).into_boxed_slice();
                                    let ptr28 = vec28.as_ptr().cast::<u8>();
                                    let len28 = vec28.len();
                                    ::core::mem::forget(vec28);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len28;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr28.cast_mut();
                                    let vec29 = (datatype27.into_bytes()).into_boxed_slice();
                                    let ptr29 = vec29.as_ptr().cast::<u8>();
                                    let len29 = vec29.len();
                                    ::core::mem::forget(vec29);
                                    *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len29;
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr29.cast_mut();
                                    match lang27 {
                                        Some(e) => {
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec30 = (e.into_bytes()).into_boxed_slice();
                                            let ptr30 = vec30.as_ptr().cast::<u8>();
                                            let len30 = vec30.len();
                                            ::core::mem::forget(vec30);
                                            *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len30;
                                            *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr30.cast_mut();
                                        }
                                        None => {
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                }
                                V32::Bnode(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec31 = (e.into_bytes()).into_boxed_slice();
                                    let ptr31 = vec31.as_ptr().cast::<u8>();
                                    let len31 = vec31.len();
                                    ::core::mem::forget(vec31);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len31;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr31.cast_mut();
                                }
                            }
                        }
                    }
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len33;
                    *base.add(0).cast::<*mut u8>() = result33;
                }
            }
            *ptr20.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len34;
            *ptr20.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result34;
        }
        Err(e) => {
            *ptr20.add(0).cast::<u8>() = (1i32) as u8;
            let vec35 = (e.into_bytes()).into_boxed_slice();
            let ptr35 = vec35.as_ptr().cast::<u8>();
            let len35 = vec35.len();
            ::core::mem::forget(vec35);
            *ptr20.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len35;
            *ptr20.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr35
                .cast_mut();
        }
    };
    ptr20
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_evaluate<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base5 = l1;
            let len5 = l2;
            for i in 0..len5 {
                let base = base5.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let l3 = *base.add(0).cast::<*mut u8>();
                    let l4 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                }
            }
            _rt::cabi_dealloc(
                base5,
                len5 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let l6 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l7 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base25 = l6;
            let len25 = l7;
            for i in 0..len25 {
                let base = base25.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let l8 = *base.add(0).cast::<*mut u8>();
                    let l9 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base24 = l8;
                    let len24 = l9;
                    for i in 0..len24 {
                        let base = base24
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l10 = *base.add(0).cast::<*mut u8>();
                            let l11 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                            let l12 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l12 {
                                0 => {
                                    let l13 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                                1 => {
                                    let l15 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l16 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l15, l16, 1);
                                    let l17 = *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l18 = *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l17, l18, 1);
                                    let l19 = i32::from(
                                        *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l19 {
                                        0 => {}
                                        _ => {
                                            let l20 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l21 = *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l20, l21, 1);
                                        }
                                    }
                                }
                                _ => {
                                    let l22 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l23 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l22, l23, 1);
                                }
                            }
                        }
                    }
                    _rt::cabi_dealloc(
                        base24,
                        len24 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
            }
            _rt::cabi_dealloc(
                base25,
                len25 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
        _ => {
            let l26 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l27 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l26, l27, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_aggregate_step_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i64,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base18 = arg0;
    let len18 = arg1;
    let mut result18 = _rt::Vec::with_capacity(len18);
    for i in 0..len18 {
        let base = base18.add(i * (8 * ::core::mem::size_of::<*const u8>()));
        let e18 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            use stardog::webfunction::types::Value as V17;
            let v17 = match l0 {
                0 => {
                    let e17 = {
                        let l1 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l2 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len3 = l2;
                        let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                        _rt::string_lift(bytes3)
                    };
                    V17::Iri(e17)
                }
                1 => {
                    let e17 = {
                        let l4 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                        let l7 = *base
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l8 = *base
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                        let l10 = i32::from(
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>(),
                        );
                        stardog::webfunction::types::Literal {
                            label: _rt::string_lift(bytes6),
                            datatype: _rt::string_lift(bytes9),
                            lang: match l10 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l11 = *base
                                            .add(6 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l12 = *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        }
                    };
                    V17::Literal(e17)
                }
                n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    let e17 = {
                        let l14 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l15 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len16 = l15;
                        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
                        _rt::string_lift(bytes16)
                    };
                    V17::Bnode(e17)
                }
            };
            v17
        };
        result18.push(e18);
    }
    _rt::cabi_dealloc(
        base18,
        len18 * (8 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result19 = T::aggregate_step(result18, arg2 as u64);
    let ptr20 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result19 {
        Ok(_) => {
            *ptr20.add(0).cast::<u8>() = (0i32) as u8;
        }
        Err(e) => {
            *ptr20.add(0).cast::<u8>() = (1i32) as u8;
            let vec21 = (e.into_bytes()).into_boxed_slice();
            let ptr21 = vec21.as_ptr().cast::<u8>();
            let len21 = vec21.len();
            ::core::mem::forget(vec21);
            *ptr20.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len21;
            *ptr20.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr21
                .cast_mut();
        }
    };
    ptr20
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_aggregate_step<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_aggregate_finish_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::aggregate_finish();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Ok(e) => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
            let stardog::webfunction::types::BindingSets { vars: vars2, rows: rows2 } = e;
            let vec4 = vars2;
            let len4 = vec4.len();
            let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                vec4.len() * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result4 = if layout4.size() != 0 {
                let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout4);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec4.into_iter().enumerate() {
                let base = result4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let vec3 = (e.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                }
            }
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result4;
            let vec15 = rows2;
            let len15 = vec15.len();
            let layout15 = _rt::alloc::Layout::from_size_align_unchecked(
                vec15.len() * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result15 = if layout15.size() != 0 {
                let ptr = _rt::alloc::alloc(layout15).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout15);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec15.into_iter().enumerate() {
                let base = result15.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let vec14 = e;
                    let len14 = vec14.len();
                    let layout14 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec14.len() * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result14 = if layout14.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout14).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout14);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec14.into_iter().enumerate() {
                        let base = result14
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let stardog::webfunction::types::Binding {
                                name: name5,
                                value: value5,
                            } = e;
                            let vec6 = (name5.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                            use stardog::webfunction::types::Value as V13;
                            match value5 {
                                V13::Iri(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec7 = (e.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr7.cast_mut();
                                }
                                V13::Literal(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let stardog::webfunction::types::Literal {
                                        label: label8,
                                        datatype: datatype8,
                                        lang: lang8,
                                    } = e;
                                    let vec9 = (label8.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    let vec10 = (datatype8.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                    match lang8 {
                                        Some(e) => {
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec11 = (e.into_bytes()).into_boxed_slice();
                                            let ptr11 = vec11.as_ptr().cast::<u8>();
                                            let len11 = vec11.len();
                                            ::core::mem::forget(vec11);
                                            *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len11;
                                            *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr11.cast_mut();
                                        }
                                        None => {
                                            *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                }
                                V13::Bnode(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec12 = (e.into_bytes()).into_boxed_slice();
                                    let ptr12 = vec12.as_ptr().cast::<u8>();
                                    let len12 = vec12.len();
                                    ::core::mem::forget(vec12);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len12;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr12.cast_mut();
                                }
                            }
                        }
                    }
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
                    *base.add(0).cast::<*mut u8>() = result14;
                }
            }
            *ptr1.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
            *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result15;
        }
        Err(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec16 = (e.into_bytes()).into_boxed_slice();
            let ptr16 = vec16.as_ptr().cast::<u8>();
            let len16 = vec16.len();
            ::core::mem::forget(vec16);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr16
                .cast_mut();
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_aggregate_finish<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base5 = l1;
            let len5 = l2;
            for i in 0..len5 {
                let base = base5.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let l3 = *base.add(0).cast::<*mut u8>();
                    let l4 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                }
            }
            _rt::cabi_dealloc(
                base5,
                len5 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let l6 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l7 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base25 = l6;
            let len25 = l7;
            for i in 0..len25 {
                let base = base25.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                {
                    let l8 = *base.add(0).cast::<*mut u8>();
                    let l9 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base24 = l8;
                    let len24 = l9;
                    for i in 0..len24 {
                        let base = base24
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l10 = *base.add(0).cast::<*mut u8>();
                            let l11 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                            let l12 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l12 {
                                0 => {
                                    let l13 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                                1 => {
                                    let l15 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l16 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l15, l16, 1);
                                    let l17 = *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l18 = *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l17, l18, 1);
                                    let l19 = i32::from(
                                        *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l19 {
                                        0 => {}
                                        _ => {
                                            let l20 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l21 = *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l20, l21, 1);
                                        }
                                    }
                                }
                                _ => {
                                    let l22 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l23 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l22, l23, 1);
                                }
                            }
                        }
                    }
                    _rt::cabi_dealloc(
                        base24,
                        len24 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
            }
            _rt::cabi_dealloc(
                base25,
                len25 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
        _ => {
            let l26 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l27 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l26, l27, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_cardinality_estimate_cabi<T: Guest>(
    arg0: f64,
    arg1: i32,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base18 = arg2;
    let len18 = arg3;
    let mut result18 = _rt::Vec::with_capacity(len18);
    for i in 0..len18 {
        let base = base18.add(i * (8 * ::core::mem::size_of::<*const u8>()));
        let e18 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            use stardog::webfunction::types::Value as V17;
            let v17 = match l0 {
                0 => {
                    let e17 = {
                        let l1 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l2 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len3 = l2;
                        let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                        _rt::string_lift(bytes3)
                    };
                    V17::Iri(e17)
                }
                1 => {
                    let e17 = {
                        let l4 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                        let l7 = *base
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l8 = *base
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                        let l10 = i32::from(
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>(),
                        );
                        stardog::webfunction::types::Literal {
                            label: _rt::string_lift(bytes6),
                            datatype: _rt::string_lift(bytes9),
                            lang: match l10 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l11 = *base
                                            .add(6 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l12 = *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        }
                    };
                    V17::Literal(e17)
                }
                n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    let e17 = {
                        let l14 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l15 = *base
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len16 = l15;
                        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
                        _rt::string_lift(bytes16)
                    };
                    V17::Bnode(e17)
                }
            };
            v17
        };
        result18.push(e18);
    }
    _rt::cabi_dealloc(
        base18,
        len18 * (8 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result19 = T::cardinality_estimate(
        stardog::webfunction::types::Cardinality {
            value: arg0,
            accuracy: stardog::webfunction::types::Accuracy::_lift(arg1 as u8),
        },
        result18,
    );
    let ptr20 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result19 {
        Ok(e) => {
            *ptr20.add(0).cast::<u8>() = (0i32) as u8;
            let stardog::webfunction::types::Cardinality {
                value: value21,
                accuracy: accuracy21,
            } = e;
            *ptr20.add(8).cast::<f64>() = _rt::as_f64(value21);
            *ptr20.add(16).cast::<u8>() = (accuracy21.clone() as i32) as u8;
        }
        Err(e) => {
            *ptr20.add(0).cast::<u8>() = (1i32) as u8;
            let vec22 = (e.into_bytes()).into_boxed_slice();
            let ptr22 = vec22.as_ptr().cast::<u8>();
            let len22 = vec22.len();
            ::core::mem::forget(vec22);
            *ptr20.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
            *ptr20.add(8).cast::<*mut u8>() = ptr22.cast_mut();
        }
    };
    ptr20
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_cardinality_estimate<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(8).cast::<*mut u8>();
            let l2 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_doc_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::doc();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let stardog::webfunction::types::BindingSets { vars: vars2, rows: rows2 } = result0;
    let vec4 = vars2;
    let len4 = vec4.len();
    let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
        vec4.len() * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result4 = if layout4.size() != 0 {
        let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout4);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec4.into_iter().enumerate() {
        let base = result4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        {
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
        }
    }
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr1.add(0).cast::<*mut u8>() = result4;
    let vec15 = rows2;
    let len15 = vec15.len();
    let layout15 = _rt::alloc::Layout::from_size_align_unchecked(
        vec15.len() * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result15 = if layout15.size() != 0 {
        let ptr = _rt::alloc::alloc(layout15).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout15);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec15.into_iter().enumerate() {
        let base = result15.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        {
            let vec14 = e;
            let len14 = vec14.len();
            let layout14 = _rt::alloc::Layout::from_size_align_unchecked(
                vec14.len() * (10 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result14 = if layout14.size() != 0 {
                let ptr = _rt::alloc::alloc(layout14).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout14);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec14.into_iter().enumerate() {
                let base = result14.add(i * (10 * ::core::mem::size_of::<*const u8>()));
                {
                    let stardog::webfunction::types::Binding {
                        name: name5,
                        value: value5,
                    } = e;
                    let vec6 = (name5.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                    use stardog::webfunction::types::Value as V13;
                    match value5 {
                        V13::Iri(e) => {
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                        V13::Literal(e) => {
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let stardog::webfunction::types::Literal {
                                label: label8,
                                datatype: datatype8,
                                lang: lang8,
                            } = e;
                            let vec9 = (label8.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                            let vec10 = (datatype8.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                            match lang8 {
                                Some(e) => {
                                    *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec11 = (e.into_bytes()).into_boxed_slice();
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    ::core::mem::forget(vec11);
                                    *base
                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *base
                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr11.cast_mut();
                                }
                                None => {
                                    *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        V13::Bnode(e) => {
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (2i32) as u8;
                            let vec12 = (e.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    }
                }
            }
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
            *base.add(0).cast::<*mut u8>() = result14;
        }
    }
    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result15;
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_doc<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base4 = l0;
    let len4 = l1;
    for i in 0..len4 {
        let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
        }
    }
    _rt::cabi_dealloc(
        base4,
        len4 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let l5 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l6 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base24 = l5;
    let len24 = l6;
    for i in 0..len24 {
        let base = base24.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        {
            let l7 = *base.add(0).cast::<*mut u8>();
            let l8 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base23 = l7;
            let len23 = l8;
            for i in 0..len23 {
                let base = base23.add(i * (10 * ::core::mem::size_of::<*const u8>()));
                {
                    let l9 = *base.add(0).cast::<*mut u8>();
                    let l10 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l9, l10, 1);
                    let l11 = i32::from(
                        *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l11 {
                        0 => {
                            let l12 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                        1 => {
                            let l14 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l15 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l14, l15, 1);
                            let l16 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l17 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l16, l17, 1);
                            let l18 = i32::from(
                                *base
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l18 {
                                0 => {}
                                _ => {
                                    let l19 = *base
                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l20 = *base
                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l19, l20, 1);
                                }
                            }
                        }
                        _ => {
                            let l21 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l22 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l21, l22, 1);
                        }
                    }
                }
            }
            _rt::cabi_dealloc(
                base23,
                len23 * (10 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
    }
    _rt::cabi_dealloc(
        base24,
        len24 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
}
pub trait Guest {
    fn evaluate(args: _rt::Vec<Value>) -> Result<BindingSets, _rt::String>;
    fn aggregate_step(args: _rt::Vec<Value>, mult: u64) -> Result<(), _rt::String>;
    fn aggregate_finish() -> Result<BindingSets, _rt::String>;
    fn cardinality_estimate(
        input: Cardinality,
        args: _rt::Vec<Value>,
    ) -> Result<Cardinality, _rt::String>;
    fn doc() -> BindingSets;
}
#[doc(hidden)]
macro_rules! __export_world_webfunction_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "evaluate")] unsafe extern "C" fn
        export_evaluate(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_evaluate_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_evaluate")] unsafe extern "C" fn
        _post_return_evaluate(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_evaluate::<$ty > (arg0) } } #[unsafe (export_name =
        "aggregate-step")] unsafe extern "C" fn export_aggregate_step(arg0 : * mut u8,
        arg1 : usize, arg2 : i64,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_aggregate_step_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe (export_name
        = "cabi_post_aggregate-step")] unsafe extern "C" fn
        _post_return_aggregate_step(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_aggregate_step::<$ty > (arg0) } } #[unsafe (export_name =
        "aggregate-finish")] unsafe extern "C" fn export_aggregate_finish() -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_aggregate_finish_cabi::<$ty > () } }
        #[unsafe (export_name = "cabi_post_aggregate-finish")] unsafe extern "C" fn
        _post_return_aggregate_finish(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_aggregate_finish::<$ty > (arg0) } } #[unsafe (export_name =
        "cardinality-estimate")] unsafe extern "C" fn export_cardinality_estimate(arg0 :
        f64, arg1 : i32, arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_cardinality_estimate_cabi::<$ty > (arg0, arg1, arg2,
        arg3) } } #[unsafe (export_name = "cabi_post_cardinality-estimate")] unsafe
        extern "C" fn _post_return_cardinality_estimate(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_cardinality_estimate::<$ty > (arg0) } }
        #[unsafe (export_name = "doc")] unsafe extern "C" fn export_doc() -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_doc_cabi::<$ty > () } } #[unsafe
        (export_name = "cabi_post_doc")] unsafe extern "C" fn _post_return_doc(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_doc::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_webfunction_cabi;
#[repr(align(8))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 8 + 4 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 8 + 4 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod stardog {
    pub mod webfunction {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct Literal {
                pub label: _rt::String,
                pub datatype: _rt::String,
                pub lang: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for Literal {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Literal")
                        .field("label", &self.label)
                        .field("datatype", &self.datatype)
                        .field("lang", &self.lang)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Value {
                Iri(_rt::String),
                Literal(Literal),
                Bnode(_rt::String),
            }
            impl ::core::fmt::Debug for Value {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Value::Iri(e) => f.debug_tuple("Value::Iri").field(e).finish(),
                        Value::Literal(e) => {
                            f.debug_tuple("Value::Literal").field(e).finish()
                        }
                        Value::Bnode(e) => {
                            f.debug_tuple("Value::Bnode").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct Binding {
                pub name: _rt::String,
                pub value: Value,
            }
            impl ::core::fmt::Debug for Binding {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Binding")
                        .field("name", &self.name)
                        .field("value", &self.value)
                        .finish()
                }
            }
            pub type BindingSet = _rt::Vec<Binding>;
            #[derive(Clone)]
            pub struct BindingSets {
                pub vars: _rt::Vec<_rt::String>,
                pub rows: _rt::Vec<BindingSet>,
            }
            impl ::core::fmt::Debug for BindingSets {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("BindingSets")
                        .field("vars", &self.vars)
                        .field("rows", &self.rows)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Accuracy {
                Verified,
                Injected,
                Accurate,
                MostlyAccurate,
                ProbablyAccurate,
                PossiblyOff,
                ProbablyOff,
                Random,
            }
            impl ::core::fmt::Debug for Accuracy {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Accuracy::Verified => {
                            f.debug_tuple("Accuracy::Verified").finish()
                        }
                        Accuracy::Injected => {
                            f.debug_tuple("Accuracy::Injected").finish()
                        }
                        Accuracy::Accurate => {
                            f.debug_tuple("Accuracy::Accurate").finish()
                        }
                        Accuracy::MostlyAccurate => {
                            f.debug_tuple("Accuracy::MostlyAccurate").finish()
                        }
                        Accuracy::ProbablyAccurate => {
                            f.debug_tuple("Accuracy::ProbablyAccurate").finish()
                        }
                        Accuracy::PossiblyOff => {
                            f.debug_tuple("Accuracy::PossiblyOff").finish()
                        }
                        Accuracy::ProbablyOff => {
                            f.debug_tuple("Accuracy::ProbablyOff").finish()
                        }
                        Accuracy::Random => f.debug_tuple("Accuracy::Random").finish(),
                    }
                }
            }
            impl Accuracy {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Accuracy {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Accuracy::Verified,
                        1 => Accuracy::Injected,
                        2 => Accuracy::Accurate,
                        3 => Accuracy::MostlyAccurate,
                        4 => Accuracy::ProbablyAccurate,
                        5 => Accuracy::PossiblyOff,
                        6 => Accuracy::ProbablyOff,
                        7 => Accuracy::Random,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Cardinality {
                pub value: f64,
                pub accuracy: Accuracy,
            }
            impl ::core::fmt::Debug for Cardinality {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Cardinality")
                        .field("value", &self.value)
                        .field("accuracy", &self.accuracy)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_webfunction_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_webfunction_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_webfunction_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:stardog:webfunction@0.2.0:webfunction:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 787] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x91\x05\x01A\x02\x01\
A\x16\x01B\x11\x01ks\x01r\x03\x05labels\x08datatypes\x04lang\0\x04\0\x07literal\x03\
\0\x01\x01q\x03\x03iri\x01s\0\x07literal\x01\x02\0\x05bnode\x01s\0\x04\0\x05valu\
e\x03\0\x03\x01r\x02\x04names\x05value\x04\x04\0\x07binding\x03\0\x05\x01p\x06\x04\
\0\x0bbinding-set\x03\0\x07\x01ps\x01p\x08\x01r\x02\x04vars\x09\x04rows\x0a\x04\0\
\x0cbinding-sets\x03\0\x0b\x01m\x08\x08verified\x08injected\x08accurate\x0fmostl\
y-accurate\x11probably-accurate\x0cpossibly-off\x0cprobably-off\x06random\x04\0\x08\
accuracy\x03\0\x0d\x01r\x02\x05valueu\x08accuracy\x0e\x04\0\x0bcardinality\x03\0\
\x0f\x03\0\x1fstardog:webfunction/types@0.2.0\x05\0\x02\x03\0\0\x05value\x03\0\x05\
value\x03\0\x01\x02\x03\0\0\x0cbinding-sets\x03\0\x0cbinding-sets\x03\0\x03\x02\x03\
\0\0\x0bcardinality\x03\0\x0bcardinality\x03\0\x05\x01p\x02\x01j\x01\x04\x01s\x01\
@\x01\x04args\x07\0\x08\x04\0\x08evaluate\x01\x09\x01j\0\x01s\x01@\x02\x04args\x07\
\x04multw\0\x0a\x04\0\x0eaggregate-step\x01\x0b\x01@\0\0\x08\x04\0\x10aggregate-\
finish\x01\x0c\x01j\x01\x06\x01s\x01@\x02\x05input\x06\x04args\x07\0\x0d\x04\0\x14\
cardinality-estimate\x01\x0e\x01@\0\0\x04\x04\0\x03doc\x01\x0f\x04\0%stardog:web\
function/webfunction@0.2.0\x04\0\x0b\x11\x01\0\x0bwebfunction\x03\0\0\0G\x09prod\
ucers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
